name: CI

on:
    push:
        paths-ignore:
            - "docs/**"
            - "*.md"
    pull_request:
        paths-ignore:
            - "docs/**"
            - "*.md"

jobs:
    lint:
        name: Lint Code
        if: github.event.pull_request.draft == false
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2.3.4
            - name: Run PSScriptAnalyzer
              uses: devblackops/github-action-psscriptanalyzer@v2.3.1
              with:
                  repoToken: ${{ secrets.GITHUB_TOKEN }}

    commit-lint:
        name: Lint Commit Messages
        if: github.event.pull_request.draft == false
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2.3.4
              with:
                  fetch-depth: 0
            - uses: wagoid/commitlint-github-action@v3.0.6

    release:
        name: Create/Update Release Pull Request
        if: github.ref == 'refs/heads/master'
        needs: [commit-lint, lint]
        runs-on: ubuntu-latest
        steps:
            - name: Release Please
              id: release
              uses: GoogleCloudPlatform/release-please-action@v2.24.1
              with:
                  changelog-types: '[ { "type": "feat", "section": "Features", "hidden": false }, { "type": "fix", "section": "Bug Fixes", "hidden": false }, { "type": "build", "section": "Dependencies", "hidden": false }, { "type": "chore", "section": "Miscellaneous", "hidden": false }, { "type": "ci", "section": "Miscellaneous", "hidden": false }, { "type": "perf", "section": "Performance", "hidden": false }, { "type": "refactor", "section": "Miscellaneous", "hidden": false }, { "type": "style", "section": "Miscellaneous", "hidden": false }, { "type": "docs", "section": "Documentation", "hidden": false }]'
                  release-type: simple
