name: CI

on:
    push:
        branches:
            - master
        paths-ignore:
            - 'docs/**'
            - '*.md'
    pull_request:
        branches:
            - master
        paths-ignore:
            - 'docs/**'
            - '*.md'
        types: [opened, ready_for_review, reopened, synchronize]

jobs:
    lint:
        name: Lint Code
        if: github.event.pull_request.draft == false
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2.3.5
            - name: Run PSScriptAnalyzer
              uses: devblackops/github-action-psscriptanalyzer@v2.4.0
              with:
                  repoToken: ${{ secrets.GITHUB_TOKEN }}

    commit-lint:
        name: Lint Commit Messages
        if: >
            github.event.pull_request.draft == false &&
            github.actor != 'dependabot[bot]'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2.3.5
              with:
                  fetch-depth: 0
            - uses: wagoid/commitlint-github-action@v4.1.9

    # This job is used to save the PR number in an artifact, for use in the automerge.yml workflow
    save-pr-number:
        name: Save PR Number
        if: >
            github.event.pull_request.draft == false && 
            github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2.3.5
            - name: Save PR Number
              run: |
                  mkdir -p ./pr
                  echo ${{ github.event.number }} > ./pr/NR
            - uses: actions/upload-artifact@v2.2.4
              with:
                  name: pr
                  path: pr/
