name: CI

on:
    push:
        paths-ignore:
            - "docs/**"
            - "*.md"
    pull_request:
        paths-ignore:
            - "docs/**"
            - "*.md"

jobs:
    lint:
        name: Lint Code
        if: github.event.pull_request.draft == false
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2.3.4
            - name: Run PSScriptAnalyzer
              uses: devblackops/github-action-psscriptanalyzer@v2.3.1
              with:
                  repoToken: ${{ secrets.GITHUB_TOKEN }}

    commit-lint:
        name: Lint Commit Messages
        if: github.event.pull_request.draft == false
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2.3.4
              with:
                  fetch-depth: 0
            - uses: wagoid/commitlint-github-action@v3.1.4

    # This job is used to save the PR number in an artifact, for use in the automerge.yml workflow
    save-pr-number:
        name: Save PR Number
        if: >
            github.event.pull_request.draft == false && 
            github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2.3.4
            - name: Save PR Number
              run: |
                  mkdir -p ./pr
                  echo ${{ github.event.number }} > ./pr/NR
            - uses: actions/upload-artifact@v2.2.4
              with:
                  name: pr
                  path: pr/
